name: Ilan Tarama Botu

on:
  schedule:
    - cron: '0 */6 * * *'  # Her 6 saatte bir çalışır (istersen ayarlarız)
  workflow_dispatch:  # Manuel çalıştırmaya da izin verir

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Repo'yu klonla
      uses: actions/checkout@v4

    - name: Python'u kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Gerekli paketleri yükle
      run: |
        pip install -r requirements.txt

    - name: Botu çalıştır
      run: |
        python ilan-tarama.py
